// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcQuEw8omgQqAzKADWpzyzGKwnT70wS9I',
    appId: '1:697424536642:web:08836b4d8048ace8c979db',
    messagingSenderId: '697424536642',
    projectId: 'terrawizz-1b28b',
    authDomain: 'terrawizz-1b28b.firebaseapp.com',
    storageBucket: 'terrawizz-1b28b.appspot.com',
    measurementId: 'G-PDG2JTGB6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3J6F0CWLPi7gHgsPnSDwoQFtsX6ctnmo',
    appId: '1:697424536642:android:47fc92d17c02d687c979db',
    messagingSenderId: '697424536642',
    projectId: 'terrawizz-1b28b',
    storageBucket: 'terrawizz-1b28b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5xKGQMXEGJPmxSE1nngv9bTI1fnNMafg',
    appId: '1:697424536642:ios:30084fadbe86b7e4c979db',
    messagingSenderId: '697424536642',
    projectId: 'terrawizz-1b28b',
    storageBucket: 'terrawizz-1b28b.appspot.com',
    iosBundleId: 'com.example.terrawizz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5xKGQMXEGJPmxSE1nngv9bTI1fnNMafg',
    appId: '1:697424536642:ios:30084fadbe86b7e4c979db',
    messagingSenderId: '697424536642',
    projectId: 'terrawizz-1b28b',
    storageBucket: 'terrawizz-1b28b.appspot.com',
    iosBundleId: 'com.example.terrawizz',
  );
}
